services:

  web:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - ${PORT:-80}:80 
    volumes:
      - ./www/public:/var/www/public
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./config/ssl:/etc/ssl
    depends_on:
      - php

  php:
    build: ./docker/php
    container_name: php
    volumes:
      - ./www/public:/var/www/public
      - ./config/php/php.ini:/usr/local/etc/php/php.ini

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: always
    volumes:
      - ./db:/var/lib/mysql
      - ./config/mysql/my.cnf:/etc/mysql/my.cnf
    environment:
      - MYSQL_ROOT_PASSWORD=${PASSWORD:-12345}
      - MYSQL_DATABASE=${DATABASE:-mydb}
      - MYSQL_USER=${USER:-pma}
      - MYSQL_PASSWORD=${PASSWORD:-12345}

  pma:
    image: phpmyadmin/phpmyadmin:latest
    container_name: pma
    restart: always
    volumes:
      - ./config/pma/config.inc.php:/etc/phpmyadmin/config.inc.php
    environment:
      PMA_HOST: mariadb
    depends_on:
      - mariadb
